services:
    ml_platform:
        image: ml_platform:latest
        container_name: ml_platform
        env_file:
            - .env
        depends_on:
            - mlflow

    mlflow:
        image: ghcr.io/mlflow/mlflow:v2.19.0
        ports:
        - "5002:5000"
        command: >
            mlflow server --host 0.0.0.0
